### ISSUE TITLE
Has anyone had any luck packaging up a shiny app with pyinstaller?

### ISSUE THREAD

**Issue by ChandlerTayek** [rstudio/py-shiny#298]
I know this might be an odd request but I'm trying to use py-shiny as the GUI front-end of the tools that I distribute to co-workers to use.

App I'm trying to package up, also the "Getting Started" app:
```python
from shiny import App, render, ui
import sys

app_ui = ui.page_fluid(
    ui.h2("Hello Shiny!"),
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
app.run()
```
For reference this is the command I used with pyinstaller:
`pyinstaller app.py`

When opening the `.exe` that gets created. The server seems to be working correctly with this output:
```
←[32mINFO←[0m:     Started server process [←[36m42132←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
```

I get this error when going to `localhost:8000` in my browser which normally works outside of the `.exe` for me:

```
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "shiny\_app.py", line 223, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\exceptions.py", line 75, in __call__
  File "starlette\middleware\exceptions.py", line 64, in __call__
  File "starlette\routing.py", line 680, in __call__
  File "starlette\routing.py", line 275, in handle
  File "starlette\routing.py", line 65, in app
  File "shiny\_app.py", line 282, in _on_root_request_cb
  File "shiny\_app.py", line 336, in _ensure_web_dependencies
  File "shiny\_app.py", line 353, in _register_web_dependency
  File "starlette\staticfiles.py", line 55, in __init__
RuntimeError: Directory 'D:\scratch\shiny_test_apps\getting_started_app\my_app\dist\app\shiny\www/shared/requirejs/' does not exist
```
I apologize if this is a bad question but I'm just curious if anyone has any ideas on what options I could use to maybe get this to work with pyinstaller.

**Comment by ChandlerTayek** [comment]
I'm closing this issue because I found a solution:

`pyinstaller app.py --add-data '<path to shiny site-package>;./shiny''

I'm using Windows and I had to use my full windows (with "\" path) in the place of <path to shiny site-package>` above.
