### ISSUE TITLE
`ui.nav()` doesn't handle `Tagifiable` input correctly

### ISSUE THREAD

**Issue by cpsievert** [rstudio/py-shiny#337]
Discovered via https://github.com/rstudio/py-shiny/issues/332. Here is a more minimal demonstration of  the problem:

```py
from shiny import ui

class Foo:
    def tagify(self):
        return ui.div()

res = ui.navset_tab(ui.nav("a", Foo()))

print(ui.TagList(res).render())
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 226, in render
    return {"dependencies": deps, "html": cp.get_html_string()}
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 250, in get_html_string
    html_ += line_prefix + child.get_html_string(indent, eol)
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 576, in get_html_string
    html_ += self.children.get_html_string(
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 250, in get_html_string
    html_ += line_prefix + child.get_html_string(indent, eol)
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 576, in get_html_string
    html_ += self.children.get_html_string(
  File "/Users/cpsievert/github/py-htmltools/htmltools/_core.py", line 254, in get_html_string
    raise RuntimeError(
RuntimeError: Encountered a non-tagified object. x.tagify() must be called before x.render()
```

**Comment by bartverweire** [comment]
Hi,

it seems that this pull request still has not been accepted. On the other hand, the originating issue, i.e. the input_slider that breaks in a double navset configuration, is still not solved.
Are there any other workarounds ? I think, for a more complex application, a nested navset configuration is very common.

Thanks,

Bart
