### ISSUE TITLE
asyncio.exceptions.CancelledError sometimes when stoping pyshiny app via ctrl + c

### ISSUE THREAD

**Issue by astayleraz** [rstudio/py-shiny#365]
Test steps:

1. Install workbench 2022.12.0-daily+286.pro3 on an ec2 instance with the local launcher. I was using ubuntu20
2. Create a vs code session.
3. Run the following commands in the terminal.
4. `mkdir my-app; cd my-app`
5. `python3 -m venv .venv; . .venv/bin/activate`
6. `pip install --upgrade pip`
7. `pip install shiny --extra-index-url=https://pyshiny.netlify.app/pypi; pip show shiny`
8. `shiny create demo_app`
9. `cd demo_app`
10. `shiny run --reload`
11. Click the proxy link for the app when it shows in the Posit workbench menu on the left.
12. Go back to the terminal and hit ctrl + c

Note: You may need to repeat steps 10-12 a few times to see the error. I have seen this error in VS Code, JupyterLab, and RStudio sessions.

Expected results:
The app should terminate with no issues or errors and the user should see the text `Application shutdown complete` in the terminal.

Actual results.
asyncio.exceptions.CancelledError sometimes when stoping pyshiny app via ctrl + c. Full error stack below:

```
(.venv) andrew@ip-172-98-29-238:~/my-app/demo_app$ shiny run --reload
INFO:     Will watch for changes in these directories: ['/home/andrew/my-app/demo_app']
INFO:     Uvicorn running on https://ec2-34-220-66-81.us-west-2.compute.amazonaws.com/s/038723c9ab5a7a416c856/p/1316efa7/ (Press CTRL+C to quit)
INFO:     Started reloader process [25683] using StatReload
INFO:     Started server process [25687]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
^CINFO:     Shutting down
INFO:     Finished server process [25687]
ERROR:    Traceback (most recent call last):
  File "/home/andrew/my-app/.venv/lib/python3.9/site-packages/starlette/routing.py", line 674, in lifespan
    await receive()
  File "/home/andrew/my-app/.venv/lib/python3.9/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/opt/python/3.9.5/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError
```

**Comment by astayleraz** [comment]
We see this in RStudio sessions as well. 
![Screen Shot 2022-10-28 at 11 10 03 AM](https://user-images.githubusercontent.com/1482677/198704048-c89585a4-9124-44bb-bff1-7fbf7d74fd7f.png)
