### ISSUE TITLE
`input_radio_buttons` should accept tuple for choices

### ISSUE THREAD

**Issue by wch** [rstudio/py-shiny#410]
`input_radio_buttons` throws an error if `choices` is a tuple instead of a list or dict. It should accept tuples.

```
from shiny import ui
ui.input_radio_buttons("x", "x", ("a", "b"))

Traceback (most recent call last):
  File "<exec>", line 2, in <module>
  File "/lib/python3.10/site-packages/shiny/ui/_input_check_radio.py", line 255, in input_radio_buttons
    options = _generate_options(
  File "/lib/python3.10/site-packages/shiny/ui/_input_check_radio.py", line 286, in _generate_options
    selected = list(choicez.keys())[0]
AttributeError: 'tuple' object has no attribute 'keys'
```

The same is true for `input_checkbox_group`.

**Comment by schloerke** [comment]
Related: https://github.com/rstudio/py-shiny/pull/426/files#diff-0c6ce3cb9175c27078d652044156e892b8aa26f98787877cbe4294d5e24fdc63
