### ISSUE TITLE
Install fails in mac M1, missing immutable

### ISSUE THREAD

**Issue by tr31zh** [rstudio/py-shiny#593]
**Computer**: Mac M1
**Python**: 3.11.3
**Env**: conda

**Description**:
When installing with pip install shiny error ModuleNotFoundError: No module named immutables

**Dump**:
Collecting shinywidgets
  Using cached shinywidgets-0.2.1-py3-none-any.whl (1.8 MB)
Requirement already satisfied: ipywidgets>=7.6.5 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from shinywidgets) (8.0.6)
Requirement already satisfied: jupyter-core in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from shinywidgets) (5.3.1)
Collecting shiny>=0.3.0 (from shinywidgets)
  Using cached shiny-0.4.0-py3-none-any.whl (2.2 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from shinywidgets) (2.8.2)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from ipywidgets>=7.6.5->shinywidgets) (6.23.3)
Requirement already satisfied: ipython>=6.1.0 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from ipywidgets>=7.6.5->shinywidgets) (8.14.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from ipywidgets>=7.6.5->shinywidgets) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.7 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from ipywidgets>=7.6.5->shinywidgets) (4.0.7)
Requirement already satisfied: jupyterlab-widgets~=3.0.7 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from ipywidgets>=7.6.5->shinywidgets) (3.0.7)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from python-dateutil>=2.8.2->shinywidgets) (1.16.0)
Requirement already satisfied: typing-extensions>=4.0.1 in /opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages (from shiny>=0.3.0->shinywidgets) (4.7.1)
Collecting uvicorn>=0.16.0 (from shiny>=0.3.0->shinywidgets)
  Using cached uvicorn-0.22.0-py3-none-any.whl (58 kB)
Collecting starlette>=0.17.1 (from shiny>=0.3.0->shinywidgets)
  Using cached starlette-0.28.0-py3-none-any.whl (68 kB)
Collecting contextvars>=2.4 (from shiny>=0.3.0->shinywidgets)
  Using cached contextvars-2.4.tar.gz (9.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mk/p6fn1z5s5p399vpdyhlnyzcm0000gn/T/pip-install-r5btqawr/contextvars_e52e4338fddf47c7ab4ea4f220b9d84a/setup.py", line 9, in <module>
          setuptools.setup(
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/dist.py", line 934, in finalize_options
          for ep in sorted(loaded, key=by_order):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/setuptools/dist.py", line 933, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
                                 ^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/npe2/__init__.py", line 10, in <module>
          from ._inspection._fetch import fetch_manifest, get_manifest_from_wheel
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/site-packages/npe2/_inspection/_fetch.py", line 26, in <module>
          from unittest.mock import patch
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/unittest/mock.py", line 26, in <module>
          import asyncio
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/asyncio/__init__.py", line 8, in <module>
          from .base_events import *
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/asyncio/base_events.py", line 40, in <module>
          from . import events
        File "/opt/homebrew/anaconda3/envs/sam/lib/python3.11/asyncio/events.py", line 14, in <module>
          import contextvars
        File "/private/var/folders/mk/p6fn1z5s5p399vpdyhlnyzcm0000gn/T/pip-install-r5btqawr/contextvars_e52e4338fddf47c7ab4ea4f220b9d84a/contextvars/__init__.py", line 4, in <module>
          import immutables
      ModuleNotFoundError: No module named 'immutables'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Quick fix**
Install immutables separately

**Comment by nealrichardson** [comment]
Something is odd with your environment since it is pulling `contextvars` from outside the conda env. But you shouldn't need that package at all: https://pypi.org/project/contextvars/ (see [here](https://github.com/MagicStack/contextvars/blob/master/contextvars/__init__.py#L4)) is a backport of the [standard library module](https://github.com/python/cpython/blob/main/Lib/contextvars.py), which was added in python 3.7. 

Since we no longer support python < 3.8, I think we can drop the explicit contextvars reference here: https://github.com/rstudio/py-shiny/blob/main/setup.cfg#L38

Even with that fix, I still suspect you'll need to sort out (i.e delete and recreate) your environment.
