### ISSUE TITLE
Error logging on Connect is worse than local development

### ISSUE THREAD

**Issue by jcheng5** [rstudio/py-shiny#619]
Heard this from @GShotwell, maybe some errors are being emitted to stdout?

**Comment by GShotwell** [comment]
I just ran a quick test, and errors and warnings are showing up on Connect. I'm not sure what was going on with the app I was remembering, but I think we can probably close this one. 

Deployed app:

```
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.panel_title("Hello Shiny"),
    ui.layout_sidebar(
        ui.panel_sidebar(ui.input_slider("n", "N", 0, 100, 20)),
        ui.panel_main(ui.output_text_verbatim("txt")),
    ),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        raise Warning("test")
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
```

Logs generated:
```
...
2023/07/13 17:55:40.451207816 Loading code from "app"
2023/07/13 17:55:41.878616071 App type is "App"
2023/07/13 17:55:41.879934094 Starting server...
2023/07/13 17:55:43.752632009 Traceback (most recent call last):
2023/07/13 17:55:43.752649991   File "/opt/rstudio-connect/mnt/app/python/env/lib/python3.10/site-packages/shiny/session/_session.py", line 1022, in output_obs
2023/07/13 17:55:43.752695399     message[output_name] = fn()
2023/07/13 17:55:43.752697818   File "/opt/rstudio-connect/mnt/app/python/env/lib/python3.10/site-packages/shiny/render/_render.py", line 115, in __call__
2023/07/13 17:55:43.752704457     return _utils.run_coro_sync(self._run())
2023/07/13 17:55:43.752705103   File "/opt/rstudio-connect/mnt/app/python/env/lib/python3.10/site-packages/shiny/_utils.py", line 296, in run_coro_sync
2023/07/13 17:55:43.752711257     coro.send(None)
2023/07/13 17:55:43.752711742   File "/opt/rstudio-connect/mnt/app/python/env/lib/python3.10/site-packages/shiny/render/_render.py", line 118, in _run
2023/07/13 17:55:43.752717298     res = await self._fn()
2023/07/13 17:55:43.752717857   File "/opt/rstudio-connect/mnt/app/python/env/lib/python3.10/site-packages/shiny/_utils.py", line 251, in fn_async
2023/07/13 17:55:43.752723279     return fn(*args, **kwargs)
2023/07/13 17:55:43.752723767   File "/opt/rstudio-connect/mnt/app/app.py", line 16, in txt
2023/07/13 17:55:43.752729216     raise Warning("test")
2023/07/13 17:55:43.752734013 Warning: test
```

**Comment by jcheng5** [comment]
Good to hear--thanks!
